version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_host
    environment:
      POSTGRES_DB: crypto_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crypto_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:13
    container_name: postgres_test_host
    environment:
      POSTGRES_DB: crypto_tracker_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crypto_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
