version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_host
    environment:
      POSTGRES_DB: crypto_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crypto_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
