apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-config
  namespace: cryptotracker
data:
  POSTGRES_DB: crypto_tracker_db
  POSTGRES_USER: postgres
  SPRING_PROFILES_ACTIVE: prod
  LOGGING_FILE_PATH: /logs/app.log
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crypto_tracker_db
  SPLUNK_HEC_ENABLE: "true"
  SPLUNK_HEC_SSL: "false"
