apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: cryptotracker
spec:
  selector:
    app: splunk
  ports:
    - port: 8000
      targetPort: 8000
    - port: 8088
      targetPort: 8088
