name: Create EKS Cluster

on:
  push:
    branches:
      - infra_terraform
    paths:
      - 'infra/**'
      
defaults:
  run:
    working-directory: infra

jobs:
  create-eks-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::682794874194:role/GitHubActionsEKSDeployRole
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
